DROP DATABASE IF EXISTS GuessDBtest;
CREATE DATABASE GuessDBtest;
USE GuessDBtest;

CREATE TABLE Game (
GameId INT PRIMARY KEY AUTO_INCREMENT,
Answer CHAR(4) NOT NULL,
Status VARCHAR(11) NOT NULL DEFAULT 'in progress');

CREATE TABLE Round (
RoundId INT PRIMARY KEY AUTO_INCREMENT,
Guess CHAR(4) NOT NULL,
TimeOfGuess DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
Result CHAR(18) NOT NULL DEFAULT "e:0:p:0",
GameId INT NOT NULL,
CONSTRAINT fk_Round_Game     
    FOREIGN KEY fk_Round_Game (GameId)
		REFERENCES Game (GameId));
        
